{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"LBS_V_PBI_ASC_OVERDUE_REVIEWS\",\"Use_table\",\"Use_summary sheet\",\"MH\",\"MH performance group diff SA\",\"OPPD\",\"OPPD performance group diff SA\",\"SRC\",\"Data Refresh\",\"Use_NRPF\",\"Use_No services\",\"Use_summary sheet (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "MH",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Use_table,",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Performance group] = \"MH (inc Sub Misuse)\")),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Open Allocated Team\"}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Removed Columns\",{{\"Person ID\", Order.Ascending}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Sorted Rows\",{{\"Date of Last Review\", type text}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"Person ID\"})",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "4461e859-c5b2-45cc-a673-2b47cae67aea"
      },
      {
        "name": "MH performance group diff SA",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Use_table,",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Performance group] = \"MH (inc Sub Misuse)\")),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Open Allocated Team\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Columns\", each ([Open Allocated Service Area] <> \"Mental Health\")),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Filtered Rows1\", {\"Person ID\"})",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "d3a78d0c-457d-4d59-b3ad-be9bbc674a91"
      },
      {
        "name": "OPPD",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Use_table,",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each [Performance group] = \"OPPD, etc\"),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Open Allocated Team\"}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Removed Columns\",{{\"Person ID\", Order.Ascending}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Sorted Rows\",{{\"Date of Last Review\", type text}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"Person ID\"})",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "50510797-56ab-4d3e-aab0-dc4264fbaa19"
      },
      {
        "name": "OPPD performance group diff SA",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Use_table,",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each [Performance group] = \"OPPD, etc\" and [Open Allocated Service Area] <> \"OP and PD\"),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Open Allocated Team\"}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\", {\"Person ID\"})",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "30f473d6-32d8-4b81-adda-cb1bff978702"
      },
      {
        "name": "SRC",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Use_table,",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Performance group] = \"SRC\")),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Open Allocated Team\"}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Removed Columns\",{{\"Person ID\", Order.Ascending}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Sorted Rows\",{{\"Date of Last Review\", type text}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\", {\"Person ID\"})",
          "in",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "f9fc6493-aab1-4f3f-95d6-e5981228c770"
      },
      {
        "name": "Use_NRPF",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = LBS_V_PBI_ASC_OVERDUE_REVIEWS,",
          "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Person Name\", \"Person Gender\", \"Age Band\", \"Date of Death\", \"Co-Worker\", \"Co-Worker Team\", \"Last Allocated Team\", \"Single Service Area\", \"Single Service Area Value\", \"Single Service Area Source\", \"Single Service Budget Area\", \"Single Service Budget Holder\", \"Timescale In Progress\", \"Diff Completed/Next Date\", \"Timescale Outstanding\", \"Timescale Outstanding Rank\", \"Last Review Completion Time\", \"Total Case Notes\", \"Funding type(s)\", \"Has Non Personal Budget\", \"Has Personal Budget\", \"Group Description\", \"Sub-group Description\", \"Next Action\", \"Last Review Type\", \"Date of Last Assessment\", \"Last Assessment Type\", \"Next Rev:Last Comp.Ass/Rev+1yr\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Person ID\", type text}, {\"Service Start Date\", type text}, {\"Date of Last Comp Assess/Rev\", type text}, {\"Date of Last Review\", type text}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,\"Unallocated/Not recorded\",Replacer.ReplaceValue,{\"Open Allocated Team\", \"Open Allocated Worker Team\", \"Open Allocated Worker\"}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Replaced Value\",{{\"Person ID\", Order.Ascending}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Sorted Rows\", {\"Person ID\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Duplicates\", each ([Services] = \"Home Care, NRPF\" or [Services] = \"NRPF (obsolete)\"))",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "69f211bd-a9b9-4ba1-ba92-ebcb211e724c"
      },
      {
        "name": "Use_No services",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = LBS_V_PBI_ASC_OVERDUE_REVIEWS,",
          "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Person Name\", \"Person Gender\", \"Age Band\", \"Date of Death\", \"Co-Worker\", \"Co-Worker Team\", \"Last Allocated Team\", \"Single Service Area\", \"Single Service Area Value\", \"Single Service Area Source\", \"Single Service Budget Area\", \"Single Service Budget Holder\", \"Timescale In Progress\", \"Diff Completed/Next Date\", \"Timescale Outstanding\", \"Timescale Outstanding Rank\", \"Last Review Completion Time\", \"Total Case Notes\", \"Funding type(s)\", \"Has Non Personal Budget\", \"Has Personal Budget\", \"Group Description\", \"Sub-group Description\", \"Next Action\", \"Last Review Type\", \"Date of Last Assessment\", \"Last Assessment Type\", \"Next Rev:Last Comp.Ass/Rev+1yr\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Person ID\", type text}, {\"Service Start Date\", type text}, {\"Date of Last Comp Assess/Rev\", type text}, {\"Date of Last Review\", type text}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,\"Unallocated/Not recorded\",Replacer.ReplaceValue,{\"Open Allocated Team\", \"Open Allocated Worker Team\", \"Open Allocated Worker\"}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Replaced Value\",{{\"Person ID\", Order.Ascending}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Sorted Rows\", {\"Person ID\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Duplicates\", each ([Services] = \"No Services\"))",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "41c93a47-8eb1-4302-8ae2-b315322d11df"
      },
      {
        "name": "LBS_V_PBI_ASC_OVERDUE_REVIEWS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Oracle.Database(\"\"\"swk-rep-db2.lbs.ad.southwark.gov.uk:1542/mosrep\"\"\", [HierarchicalNavigation=true]),",
          "    FW = Source{[Schema=\"FW\"]}[Data],",
          "    LBS_V_PBI_ASC_OVERDUE_REVIEWS1 = FW{[Name=\"LBS_V_PBI_ASC_OVERDUE_REVIEWS\"]}[Data]",
          "in",
          "    LBS_V_PBI_ASC_OVERDUE_REVIEWS1"
        ],
        "kind": "m",
        "lineageTag": "4c323572-e2ac-4eba-a0d9-a401fe1ecc16"
      },
      {
        "name": "Use_summary sheet (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = LBS_V_PBI_ASC_OVERDUE_REVIEWS,",
          "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Person Name\", \"Date of Death\", \"Co-Worker\", \"Co-Worker Team\", \"Last Allocated Team\", \"Single Service Area\", \"Single Service Area Value\", \"Single Service Area Source\", \"Single Service Budget Area\", \"Single Service Budget Holder\", \"Timescale In Progress\", \"Diff Completed/Next Date\", \"Timescale Outstanding\", \"Timescale Outstanding Rank\", \"Last Review Completion Time\", \"Total Case Notes\", \"Funding type(s)\", \"Has Non Personal Budget\", \"Has Personal Budget\", \"Group Description\", \"Next Action\", \"Last Review Type\", \"Date of Last Assessment\", \"Last Assessment Type\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Person ID\", type text}, {\"Service Start Date\", type text}, {\"Date of Last Comp Assess/Rev\", type text}, {\"Date of Last Review\", type text}, {\"Person Age\", Int64.Type}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,\"Unallocated/Not recorded\",Replacer.ReplaceValue,{\"Open Allocated Team\", \"Open Allocated Worker Team\", \"Open Allocated Worker\"}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Replaced Value\",{{\"Person ID\", Order.Ascending}}),",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Sorted Rows\", {\"Person ID\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Duplicates\", each ([Services] <> \"No Services\" and [Services] <> \"NRPF (obsolete)\"))",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "b03cea35-506d-449f-ab18-67ce25f22fc9"
      }
    ],
    "relationships": [
      {
        "name": "cdcf3699-c34d-437e-ba12-c6c703a9de24",
        "fromColumn": "Date",
        "fromTable": "Data Refresh",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b9ea4723-d1f3-4f07-a179-0a431403973b"
      },
      {
        "name": "effd7844-2d2a-48ae-8a07-fc67ffab856b",
        "fromColumn": "Next Rev:Last Comp.Ass/Rev+1yr",
        "fromTable": "Use_summary sheet",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_298eee84-372a-4e48-9795-341589b70949"
      },
      {
        "name": "6eb199c5-ae60-4d4f-8d36-9ac5b09c81e8",
        "fromColumn": "Person DoB",
        "fromTable": "Use_table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5c0f3688-3b9b-4317-8737-04daddb6abfb"
      },
      {
        "name": "16bdc9ef-dead-4795-9be5-ebdeeedabca9",
        "fromColumn": "Person DoB",
        "fromTable": "Use_summary sheet",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ca07ab66-3e77-4c17-b405-4ec2457300ee"
      },
      {
        "name": "4190cb41-d0d3-4d42-8004-cb6e22ed0afe",
        "fromColumn": "DateTime",
        "fromTable": "Data Refresh",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c0f5b4c3-502d-4d76-a0e5-9a5d52c7bfef"
      }
    ],
    "roles": [
      {
        "name": "MH",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ca2431b1593a4646b53a2420643a0166"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Use_table",
            "filterExpression": "[Open Allocated Service Area] == \"Mental Health\""
          }
        ]
      },
      {
        "name": "OPPD",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7127e56b33b347f6b6fecf30093204e0"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Use_table",
            "filterExpression": "[Open Allocated Service Area] == \"OP and PD\""
          }
        ]
      },
      {
        "name": "PDQ",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "14a991b1440a443dbdc564eb4bc46ceb"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Use_table",
            "filterExpression": "[Open Allocated Service Area] == \"Mental Health\" || [Open Allocated Service Area] == \"OP and PD\""
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "DateTableTemplate_75a9b48e-8e42-420a-ab5e-3bb67a415fb3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "26f8d194-a837-44f0-8624-7f2d825d83b4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "65a01287-f1ad-498c-a859-a3ce7b38ff48",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f16ee6fe-1246-47af-bb5e-17e79d588d1e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6004fe9f-fd27-40d2-b83c-c812b3357fd4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "02f61619-de47-426e-ae3d-32be704b1cee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "71922f2f-0c2a-4124-ac1c-243d2529fb94",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b5e4f995-a946-4a5e-bef8-0a7603abfc6f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1eb2120d-f230-49af-bd94-462bc9210b0f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "25e0ef63-122e-4101-b538-b06559313c51",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "dd231f2a-7590-4a34-bdb8-e119cc3e12be",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ace8084a-aeb4-4896-b5af-b348105f6000",
                "ordinal": 3
              }
            ],
            "lineageTag": "b895e386-fb97-4577-964c-a71f1e8a3caf"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "123f41f9-c691-4578-ab8b-3ccde023d611",
        "partitions": [
          {
            "name": "DateTableTemplate_75a9b48e-8e42-420a-ab5e-3bb67a415fb3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Use_table",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Person ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a2a78b8-1eaf-4d92-b236-980a1f8378e7",
            "sourceColumn": "Person ID",
            "summarizeBy": "none"
          },
          {
            "name": "Person Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1de5baa4-bde0-470f-a6eb-c542b8ec03ca",
            "sourceColumn": "Person Age",
            "summarizeBy": "none"
          },
          {
            "name": "Deceased/Alive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8559562-4cb9-4e49-9c7e-bdf36ab29937",
            "sourceColumn": "Deceased/Alive",
            "summarizeBy": "none"
          },
          {
            "name": "Open Allocated Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "009667d9-452f-4ff2-ba69-fdd7a3b5646d",
            "sourceColumn": "Open Allocated Team",
            "summarizeBy": "none"
          },
          {
            "name": "Open Allocated Worker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4ad8d3d-7845-4a42-a064-d75ade3fcf8b",
            "sourceColumn": "Open Allocated Worker",
            "summarizeBy": "none"
          },
          {
            "name": "Open Allocated Worker Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3bfcd13-1fc4-4604-a4b3-1399e8866407",
            "sourceColumn": "Open Allocated Worker Team",
            "summarizeBy": "none"
          },
          {
            "name": "Open Allocated Service Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "535be977-9229-42e0-8fbd-73dfc285c56c",
            "sourceColumn": "Open Allocated Service Area",
            "summarizeBy": "none"
          },
          {
            "name": "Services",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a53c3aae-805e-440e-ae4a-e7cfb21131ad",
            "sourceColumn": "Services",
            "summarizeBy": "none"
          },
          {
            "name": "Service Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "801e4e19-c1be-48f6-95e7-aa1bf640f335",
            "sourceColumn": "Service Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Performance group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f912f438-a5db-477a-9647-ede04c3ca025",
            "sourceColumn": "Performance group",
            "summarizeBy": "none"
          },
          {
            "name": "Has Active Services",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9b3c8ae-937b-41ee-bf91-58055d6aad15",
            "sourceColumn": "Has Active Services",
            "summarizeBy": "none"
          },
          {
            "name": "Overdue Review",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac279748-d3e7-4f5e-aecb-56033d65c301",
            "sourceColumn": "Overdue Review",
            "summarizeBy": "none"
          },
          {
            "name": "Review Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f279909b-6b12-408b-860c-314336e67cf9",
            "sourceColumn": "Review Status",
            "summarizeBy": "none"
          },
          {
            "name": "Days Since Review Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "6fbed702-eefc-42ca-b5e9-e351bd2ed40f",
            "sourceColumn": "Days Since Review Start",
            "summarizeBy": "sum"
          },
          {
            "name": "Days Until Planned Review",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5e5ccf25-07df-4271-96d9-c95a6a1b3055",
            "sourceColumn": "Days Until Planned Review",
            "summarizeBy": "sum"
          },
          {
            "name": "Date of Last Review",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fac4676-98c2-405e-b1cf-c41ed0a100c7",
            "sourceColumn": "Date of Last Review",
            "summarizeBy": "none"
          },
          {
            "name": "Days Since Last Compld Ass/Rev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "11e0f8d8-0ae9-44f0-bf47-ef2a976b051a",
            "sourceColumn": "Days Since Last Compld Ass/Rev",
            "summarizeBy": "sum"
          },
          {
            "name": "Days Overdue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "a8d61ac4-5fec-4434-8539-fd3904b42a0d",
            "sourceColumn": "Days Overdue",
            "summarizeBy": "sum"
          },
          {
            "name": "All Service Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c36772a7-e234-4b26-8ddc-df6dadde3df4",
            "sourceColumn": "All Service Types",
            "summarizeBy": "none"
          },
          {
            "name": "Date of Last Comp Assess/Rev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7fc2270-5ebf-4405-b7cc-1e3db686fa21",
            "sourceColumn": "Date of Last Comp Assess/Rev",
            "summarizeBy": "none"
          },
          {
            "name": "Person DoB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "74f78628-2734-4f6a-a275-303ae782d9da",
            "sourceColumn": "Person DoB",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5c0f3688-3b9b-4317-8737-04daddb6abfb"
                },
                "isDefault": true,
                "relationship": "6eb199c5-ae60-4d4f-8d36-9ac5b09c81e8"
              }
            ]
          },
          {
            "name": "In a placement?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "071c021b-5820-48eb-81e7-261fc3e06d03",
            "sourceColumn": "In a placement?",
            "summarizeBy": "none"
          },
          {
            "name": "Incoming\\Started review StepID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4db094f-ec37-4cf8-aa06-7934260c27a1",
            "sourceColumn": "Incoming\\Started review StepID",
            "summarizeBy": "none"
          },
          {
            "name": "Incoming\\Started Assessment ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6334576c-fa13-42fe-b317-f47dd7c86c26",
            "sourceColumn": "Incoming\\Started Assessment ID",
            "summarizeBy": "count"
          },
          {
            "name": "Completed Review StepID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "43cac14e-c19f-4b0b-84e9-fc94a20be201",
            "sourceColumn": "Completed Review StepID",
            "summarizeBy": "count"
          },
          {
            "name": "Filt_Open Allocated Worker Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "990ff083-a4da-42a5-b790-5e671ff6f0f9",
            "sourceColumn": "Filt_Open Allocated Worker Team",
            "summarizeBy": "none"
          },
          {
            "name": "Dummy_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(Use_table[Person ID]<>\"\",RIGHT(Use_table[Person ID],3))",
            "isDataTypeInferred": true,
            "lineageTag": "85745570-e990-4c2c-82af-9b2078884e97",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "25828e8c-d6f9-449a-89d5-42b89a71ec94",
        "measures": [
          {
            "name": "Count active filters",
            "expression": [
              "",
              "VAR Service_Area =IF(ISFILTERED(Use_table[Open Allocated Service Area]),1,0)",
              "VAR Reviewed_or_Overdue =IF(ISFILTERED(Use_table[Overdue Review]),1,0)",
              "VAR Open_All_Wrk_team = IF(ISFILTERED(Use_table[Open Allocated Worker Team]),1,0)",
              "VAR Has_active_serv =IF(ISFILTERED(Use_table[Has Active Services]),1,0)",
              "VAR Review_stat =IF(ISFILTERED(Use_table[Review Status]),1,0)",
              "",
              "VAR filter_count =",
              "Service_Area+Reviewed_or_Overdue+Open_All_Wrk_team+Has_active_serv+Review_stat",
              "",
              "RETURN ",
              "filter_count&\" \""
            ],
            "lineageTag": "14c2e838-bdee-45ef-9b7b-674d1f68caa6"
          },
          {
            "name": "Count active filters counter color",
            "expression": [
              "",
              "IF([Count active filters]=\"0\", \"#558AC930\", \"#9C74BB50\")"
            ],
            "lineageTag": "2c74c008-c6a4-4920-8d09-2406cede619d"
          },
          {
            "name": "Count active filters button color",
            "expression": [
              "",
              "IF([Count active filters]=\"0\",",
              "\"#9C74BB\",\"#000000\")"
            ],
            "lineageTag": "4f94f97f-db62-415b-93be-66741a10ad0e"
          },
          {
            "name": "counter color 2",
            "expression": [
              "",
              "IF([Count active filters]=\"0\", \"#558AC930\", \"#00000\")"
            ],
            "lineageTag": "8eb1efce-7e0d-41fb-82c4-0e92ff8825b5"
          }
        ],
        "partitions": [
          {
            "name": "Use_table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = LBS_V_PBI_ASC_OVERDUE_REVIEWS,",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Person Name\", \"Person Gender\", \"Age Band\", \"Date of Death\", \"Co-Worker\", \"Co-Worker Team\", \"Last Allocated Team\", \"Single Service Area\", \"Single Service Area Value\", \"Single Service Area Source\", \"Single Service Budget Area\", \"Single Service Budget Holder\", \"Timescale In Progress\", \"Diff Completed/Next Date\", \"Timescale Outstanding\", \"Timescale Outstanding Rank\", \"Last Review Completion Time\", \"Total Case Notes\", \"Funding type(s)\", \"Has Non Personal Budget\", \"Has Personal Budget\", \"Group Description\", \"Sub-group Description\", \"Next Action\", \"Last Review Type\", \"Date of Last Assessment\", \"Last Assessment Type\", \"Next Rev:Last Comp.Ass/Rev+1yr\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Person ID\", type text}, {\"Service Start Date\", type text}, {\"Date of Last Comp Assess/Rev\", type text}, {\"Date of Last Review\", type text}, {\"Incoming\\Started review StepID\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,\"Unallocated/Not recorded\",Replacer.ReplaceValue,{\"Open Allocated Team\", \"Open Allocated Worker Team\", \"Open Allocated Worker\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Replaced Value\",{{\"Person ID\", Order.Ascending}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Sorted Rows\", {\"Person ID\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Duplicates\", each ([Open Allocated Service Area] = \"Mental Health\" or [Open Allocated Service Area] = \"OP and PD\") and ([Services] <> \"No Services\" and [Services] <> \"NRPF (obsolete)\" and [Services] <> \"NRPF, NRPF (obsolete)\")),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Filtered Rows\", \"Open Allocated Worker Team\", \"Open Allocated Worker Team - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Open Allocated Worker Team - Copy\", \"Filt_Open Allocated Worker Team\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Data Refresh",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yy h:nn:ss AM/PM",
            "lineageTag": "a32be852-70a6-411d-acb5-df1809754727",
            "sourceColumn": "DateTime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c0f5b4c3-502d-4d76-a0e5-9a5d52c7bfef"
                },
                "isDefault": true,
                "relationship": "4190cb41-d0d3-4d42-8004-cb6e22ed0afe"
              }
            ]
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8297eb6b-765a-4e9b-8896-caaf609c2535",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b9ea4723-d1f3-4f07-a179-0a431403973b"
                },
                "isDefault": true,
                "relationship": "cdcf3699-c34d-437e-ba12-c6c703a9de24"
              }
            ]
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "1776127e-54a5-4fbf-acef-078c50331285",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cbfbd2c6-0df6-416a-bcc9-dc5dac344a36",
        "partitions": [
          {
            "name": "Data Refresh",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DateTime.LocalNow(),",
                "    #\"Converted to Table\" = #table(1, {{Source}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"DateTime\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns\", \"DateTime\", \"DateTime - Copy\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"DateTime - Copy\", \"Date\"}}),",
                "    #\"Extracted Date\" = Table.TransformColumns(#\"Renamed Columns1\",{{\"Date\", DateTime.Date, type date}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Extracted Date\", \"DateTime\", \"DateTime - Copy\"),",
                "    #\"Extracted Time\" = Table.TransformColumns(#\"Duplicated Column1\",{{\"DateTime - Copy\", DateTime.Time, type time}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Extracted Time\",{{\"DateTime - Copy\", \"Time\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_b9ea4723-d1f3-4f07-a179-0a431403973b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a568e42d-dcb0-487f-a27b-9c4e5933fd0a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0b991acd-a0bf-428c-ba53-0052a62d7055",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9b202b32-404c-4d41-beb5-07188bb92c3b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b40c0fd9-2d93-4cb0-a5f3-c2468aa1c5dd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "f91d289c-6dde-4bea-a4a0-9d37204be62d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "62a56512-366c-482c-bad3-06f2ba90acfc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9ee43bbf-b0c7-4218-a48c-380c83cc2ecd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a4e2faea-4ce1-4eb7-9674-80b361a68068",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "472b5525-0e9c-4aec-8c6c-c39deeeca531",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2c1459c2-76c9-40c6-a0da-f9bd31b3e333",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a4208f86-b3e3-4245-9469-5d1bf9d0f867",
                "ordinal": 3
              }
            ],
            "lineageTag": "7fd267b7-a096-483e-8722-56217f926d9f"
          }
        ],
        "isHidden": true,
        "lineageTag": "4fc1dfd7-b991-4cac-8d49-160542f061f9",
        "partitions": [
          {
            "name": "LocalDateTable_b9ea4723-d1f3-4f07-a179-0a431403973b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Data Refresh'[Date])), 1, 1), Date(Year(MAX('Data Refresh'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Use_summary sheet",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Person ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "5349a8ed-370a-4632-904b-26463d28ec01",
            "sourceColumn": "Person ID",
            "summarizeBy": "none"
          },
          {
            "name": "Person Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "93a9650c-cc1c-49a2-9029-2a9f43a6d51c",
            "sourceColumn": "Person Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Deceased/Alive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5de90bc-6ba3-48f2-b365-5d727ac21c8e",
            "sourceColumn": "Deceased/Alive",
            "summarizeBy": "none"
          },
          {
            "name": "Open Allocated Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56f89c5f-4a4a-4baa-80aa-2e6e0da180e5",
            "sourceColumn": "Open Allocated Team",
            "summarizeBy": "none"
          },
          {
            "name": "Open Allocated Worker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68971ed1-418f-4ed5-97f3-075a1bfe9b21",
            "sourceColumn": "Open Allocated Worker",
            "summarizeBy": "none"
          },
          {
            "name": "Open Allocated Worker Team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c441a12-e304-4dcd-8dbb-c3893722ed33",
            "sourceColumn": "Open Allocated Worker Team",
            "summarizeBy": "none"
          },
          {
            "name": "Open Allocated Service Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f81a3b35-261b-4f62-ae2f-94a8461931ec",
            "sourceColumn": "Open Allocated Service Area",
            "summarizeBy": "none"
          },
          {
            "name": "Services",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba07a0a4-f21b-4ca3-8742-8a8da81a7b64",
            "sourceColumn": "Services",
            "summarizeBy": "none"
          },
          {
            "name": "Service Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab495cc8-99fe-4523-9136-167f0c0b8d69",
            "sourceColumn": "Service Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Performance group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "960a15a4-1d8d-468f-bf71-60c30e4e777b",
            "sourceColumn": "Performance group",
            "summarizeBy": "none"
          },
          {
            "name": "Has Active Services",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5404a976-8bcf-44c4-bdba-8b74d711314a",
            "sourceColumn": "Has Active Services",
            "summarizeBy": "none"
          },
          {
            "name": "Overdue Review",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2330b8c1-c9b6-468e-972b-f6ecd1e60ad7",
            "sourceColumn": "Overdue Review",
            "summarizeBy": "none"
          },
          {
            "name": "Review Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "620847eb-b020-4859-88c2-7c3b3a8b496a",
            "sourceColumn": "Review Status",
            "summarizeBy": "none"
          },
          {
            "name": "Days Since Review Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d41972a8-c93f-4e74-a899-71a58dde13ef",
            "sourceColumn": "Days Since Review Start",
            "summarizeBy": "sum"
          },
          {
            "name": "Days Until Planned Review",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7ac67d82-d393-460b-b348-334fce04e69c",
            "sourceColumn": "Days Until Planned Review",
            "summarizeBy": "sum"
          },
          {
            "name": "Date of Last Review",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c65cad3-1adc-46cc-a9d3-fcd81653f57e",
            "sourceColumn": "Date of Last Review",
            "summarizeBy": "none"
          },
          {
            "name": "Date of Last Comp Assess/Rev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35d1b692-288f-4d88-8e16-839f1c1c9c43",
            "sourceColumn": "Date of Last Comp Assess/Rev",
            "summarizeBy": "none"
          },
          {
            "name": "Days Since Last Compld Ass/Rev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b84cbf6b-8b01-4570-b8b1-ae0cbdbf662b",
            "sourceColumn": "Days Since Last Compld Ass/Rev",
            "summarizeBy": "sum"
          },
          {
            "name": "Days Overdue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0bd6cae5-8bca-4d22-84fb-b82f5093fd3a",
            "sourceColumn": "Days Overdue",
            "summarizeBy": "sum"
          },
          {
            "name": "All Service Types",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9db7ee0c-d571-49b2-82ea-2e3dd19c9da8",
            "sourceColumn": "All Service Types",
            "summarizeBy": "none"
          },
          {
            "name": "Person Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12beac2a-8470-4990-a103-99e5e1acab99",
            "sourceColumn": "Person Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Age Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32770a74-1404-4a72-9f96-dbab7e764e1b",
            "sourceColumn": "Age Band",
            "summarizeBy": "none"
          },
          {
            "name": "Sub-group Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8903f876-14ba-41b0-aaac-c5116a49273c",
            "sourceColumn": "Sub-group Description",
            "summarizeBy": "none"
          },
          {
            "name": "Next Rev:Last Comp.Ass/Rev+1yr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a168f7fc-8c96-4929-9ca6-96fbf214dbde",
            "sourceColumn": "Next Rev:Last Comp.Ass/Rev+1yr",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_298eee84-372a-4e48-9795-341589b70949"
                },
                "isDefault": true,
                "relationship": "effd7844-2d2a-48ae-8a07-fc67ffab856b"
              }
            ]
          },
          {
            "name": "due_in_30?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(",
              "    OR(ISBLANK('Use_summary sheet'[Days Until Planned Review]),'Use_summary sheet'[Days Until Planned Review]>=31),\"no\", \"yes\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "bf76185d-77ff-4639-b64d-33c93674af63",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Person DoB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "907ce24a-5970-44f3-9776-80c8a8f2d259",
            "sourceColumn": "Person DoB",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ca07ab66-3e77-4c17-b405-4ec2457300ee"
                },
                "isDefault": true,
                "relationship": "16bdc9ef-dead-4795-9be5-ebdeeedabca9"
              }
            ]
          },
          {
            "name": "In a placement?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2edfc92-c3bb-4951-8814-e6afcc92b89b",
            "sourceColumn": "In a placement?",
            "summarizeBy": "none"
          },
          {
            "name": "Incoming\\Started review StepID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "21e3b8c0-a457-4f38-a8ca-e42284e7eed6",
            "sourceColumn": "Incoming\\Started review StepID",
            "summarizeBy": "count"
          },
          {
            "name": "Incoming\\Started Assessment ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d479da11-5e7a-4fb6-8832-a2449b5d819e",
            "sourceColumn": "Incoming\\Started Assessment ID",
            "summarizeBy": "count"
          },
          {
            "name": "Completed Review StepID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "426d41bf-5f79-4008-8b43-4b6505b42e33",
            "sourceColumn": "Completed Review StepID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "2710e5c6-7225-4160-a726-a6859c7d6342",
        "measures": [
          {
            "name": "Percent assessed_reviews",
            "expression": [
              "",
              "VAR _Totalreviews =",
              "    CALCULATE(",
              "        DISTINCTCOUNT('Use_summary sheet'[Person ID]),",
              "        ALL('Use_summary sheet'[Person ID]))",
              "RETURN",
              "VAR _Count_assessed =",
              "     CALCULATE(DISTINCTCOUNT('Use_summary sheet'[Person ID]),",
              "     'Use_summary sheet'[Overdue Review] = \"Reviewed/Assessed in last year\")",
              "RETURN",
              "DIVIDE(_Count_assessed,_Totalreviews)",
              "",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "b8ff27c3-a0e3-42a5-b899-2419727ee2e5"
          },
          {
            "name": "Avg_age",
            "expression": "CALCULATE(AVERAGE('Use_summary sheet'[Person Age]))",
            "formatString": "0",
            "lineageTag": "46a8710a-3d9d-46d5-bc6a-c55a9149de38"
          },
          {
            "name": "Count_of_in_31",
            "expression": [
              "CALCULATE(COUNTROWS('Use_summary sheet'),",
              "     'Use_summary sheet'[due_in_30?] = \"yes\")"
            ],
            "formatString": "0",
            "lineageTag": "2281b99b-ea8e-4217-ac8a-1a77fa5507a0"
          },
          {
            "name": "Percent_assessed_LD",
            "expression": [
              "",
              "VAR _Totalreviews_LD =",
              "    CALCULATE(DISTINCTCOUNT('Use_summary sheet'[Person ID]),'Use_summary sheet'[Open Allocated Service Area] = \"LD/AAD\")",
              "    ",
              "RETURN",
              "",
              "VAR _Count_assessed_LD =",
              "     CALCULATE(DISTINCTCOUNT('Use_summary sheet'[Person ID]), ",
              "     'Use_summary sheet'[Open Allocated Service Area] = \"LD/AAD\",",
              "     'Use_summary sheet'[Overdue Review] = \"Reviewed/Assessed in last year\")",
              "RETURN",
              "DIVIDE(_Count_assessed_LD,_Totalreviews_LD)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "57fd9ce3-6c7a-4ae1-9808-fdc27b4e6f5a"
          },
          {
            "name": "Percent_assessed_MH",
            "expression": [
              "",
              "VAR _Totalreviews_MH =",
              "    CALCULATE(DISTINCTCOUNT('Use_summary sheet'[Person ID]),'Use_summary sheet'[Open Allocated Service Area] = \"Mental Health\")",
              "    ",
              "RETURN",
              "",
              "VAR _Count_assessed_MH =",
              "     CALCULATE(DISTINCTCOUNT('Use_summary sheet'[Person ID]), ",
              "     'Use_summary sheet'[Open Allocated Service Area] = \"Mental Health\",",
              "     'Use_summary sheet'[Overdue Review] = \"Reviewed/Assessed in last year\")",
              "RETURN",
              "DIVIDE(_Count_assessed_MH,_Totalreviews_MH)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e73abd1a-249e-414c-bd5c-7c087a916103"
          },
          {
            "name": "Percent_assessed_OPPD",
            "expression": [
              "",
              "VAR _Totalreviews_OPPD =",
              "    CALCULATE(DISTINCTCOUNT('Use_summary sheet'[Person ID]),'Use_summary sheet'[Open Allocated Service Area] = \"OP and PD\")",
              "    ",
              "RETURN",
              "",
              "VAR _Count_assessed_OPPD =",
              "     CALCULATE(DISTINCTCOUNT('Use_summary sheet'[Person ID]), ",
              "     'Use_summary sheet'[Open Allocated Service Area] = \"OP and PD\",",
              "     'Use_summary sheet'[Overdue Review] = \"Reviewed/Assessed in last year\")",
              "RETURN",
              "DIVIDE(_Count_assessed_OPPD,_Totalreviews_OPPD)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "beeb7683-15d1-4b15-ae8a-43a49be9cfe9"
          },
          {
            "name": "dummy",
            "expression": [
              "",
              "    CALCULATE(",
              "        DISTINCTCOUNT('Use_summary sheet'[Person ID]),",
              "        'Use_summary sheet'[Overdue Review] = \"Reviewed/Assessed in last year\")"
            ],
            "formatString": "0",
            "lineageTag": "54248076-d2ff-4478-bad2-426f37343c66"
          }
        ],
        "partitions": [
          {
            "name": "Use_summary sheet",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = LBS_V_PBI_ASC_OVERDUE_REVIEWS,",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Person Name\", \"Date of Death\", \"Co-Worker\", \"Co-Worker Team\", \"Last Allocated Team\", \"Single Service Area\", \"Single Service Area Value\", \"Single Service Area Source\", \"Single Service Budget Area\", \"Single Service Budget Holder\", \"Timescale In Progress\", \"Diff Completed/Next Date\", \"Timescale Outstanding\", \"Timescale Outstanding Rank\", \"Last Review Completion Time\", \"Total Case Notes\", \"Funding type(s)\", \"Has Non Personal Budget\", \"Has Personal Budget\", \"Group Description\", \"Next Action\", \"Last Review Type\", \"Date of Last Assessment\", \"Last Assessment Type\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Person ID\", type text}, {\"Service Start Date\", type text}, {\"Date of Last Comp Assess/Rev\", type text}, {\"Date of Last Review\", type text}, {\"Person Age\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,\"Unallocated/Not recorded\",Replacer.ReplaceValue,{\"Open Allocated Team\", \"Open Allocated Worker Team\", \"Open Allocated Worker\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Replaced Value\",{{\"Person ID\", Order.Ascending}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Sorted Rows\", {\"Person ID\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Duplicates\", each ([Services] <> \"No Services\" and [Services] <> \"NRPF (obsolete)\" and [Services] <> \"NRPF, NRPF (obsolete)\") and ([#\"Deceased/Alive\"] = \"Alive\")),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Filtered Rows\",\"Learning Disabilities\",\"LD/AAD\",Replacer.ReplaceText,{\"Open Allocated Service Area\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_298eee84-372a-4e48-9795-341589b70949",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5dc6f153-b5cd-4445-b0c0-48be013ab9ed",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c2692850-5b30-45e7-b22a-71335be83a41",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e94fa8cd-aff5-4c51-8eab-3db3faa1ed71",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d0458cac-953d-423d-a766-9b1c688e5b8e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b70a5725-cbfa-4d69-8d31-29a3e657d0cf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cfb285b5-1986-4cc4-a5d0-7d7965b7e6f4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4be74808-7ae4-41c6-af49-40f47a3869f6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c1350ee8-660c-4558-9f18-58ec9a6c60ac",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "563464d0-e3fb-434e-b193-ff547aae9a74",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "23d21441-797a-47fb-8c28-74dafa7f8f06",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9d118f6f-73c9-4591-9456-122c54da2d79",
                "ordinal": 3
              }
            ],
            "lineageTag": "060bb84c-f713-4bdb-a007-bb51feac0b05"
          }
        ],
        "isHidden": true,
        "lineageTag": "fb1567d4-042e-418c-ab9d-b1773648f33e",
        "partitions": [
          {
            "name": "LocalDateTable_298eee84-372a-4e48-9795-341589b70949",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Use_summary sheet'[Next Rev:Last Comp.Ass/Rev+1yr])), 1, 1), Date(Year(MAX('Use_summary sheet'[Next Rev:Last Comp.Ass/Rev+1yr])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_5c0f3688-3b9b-4317-8737-04daddb6abfb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "42cf549d-b55b-46c8-b217-f4106f72205c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d0e0980c-578c-4d4e-9bab-330c4f340aae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6813b424-9cda-4ab9-ab1f-6b3bc5895104",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "584435d1-5db4-45e9-ad2a-c5ffbdfc153a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "110f3e06-a2f1-4da0-9356-3003cf096c63",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "04381309-5080-42e8-8600-81bd031ab561",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "71f53788-2359-49b7-90ca-03988fbe172c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f9c01868-6013-43ca-8572-da8e1ae2895f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9da07e29-d6d0-4ec4-8859-266aafb37f94",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f28b8849-8c96-4c4b-af02-4443b4276762",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ec512a5c-dc1b-43cb-a3b8-0c32529ac5da",
                "ordinal": 3
              }
            ],
            "lineageTag": "eec316b7-f972-4bb1-9e6c-c072ccaa5619"
          }
        ],
        "isHidden": true,
        "lineageTag": "74e01d7c-0ccf-475a-9c99-d6feda7face0",
        "partitions": [
          {
            "name": "LocalDateTable_5c0f3688-3b9b-4317-8737-04daddb6abfb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Use_table'[Person DoB])), 1, 1), Date(Year(MAX('Use_table'[Person DoB])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ca07ab66-3e77-4c17-b405-4ec2457300ee",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c20f5f9f-c4a3-4f49-8bf3-6b5ebf0fc084",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "70d6bb89-082b-41ec-8193-549df1e76ab3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4b2ab48b-5626-4531-b4b5-6c1361956c90",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "405d3dd9-6b22-48e5-9e52-9010ca3e8133",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9e277419-e8bc-4557-ad20-aea8b962f4ec",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "87565934-f6b4-44f6-8f0b-3245dee0793e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "89219a44-784e-466b-9b83-72efcb1d4e29",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5df083ee-19e0-4d5a-a852-8617f4ee3636",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "22da07f8-bc46-4260-8d01-b338f6570366",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0fa165df-8e20-4fcf-a85c-94fad96b44ae",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8cffcaf0-71c9-4f81-b0ae-2fff87683574",
                "ordinal": 3
              }
            ],
            "lineageTag": "fa94e6eb-8699-45d2-9f19-b463f087ac53"
          }
        ],
        "isHidden": true,
        "lineageTag": "3ebda8ba-93d3-42c3-9b89-f0852c1ff68a",
        "partitions": [
          {
            "name": "LocalDateTable_ca07ab66-3e77-4c17-b405-4ec2457300ee",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Use_summary sheet'[Person DoB])), 1, 1), Date(Year(MAX('Use_summary sheet'[Person DoB])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c0f5b4c3-502d-4d76-a0e5-9a5d52c7bfef",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6e0e83bf-ee79-475b-977b-9bae8b201675",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "99a100ca-f0b8-44e4-a549-78cbc7062e7d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "99f97eac-4f5e-4b79-80f9-68f8c2f81fdb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9dec112d-8a9b-44e7-abb3-67e1718d465f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "63ac3bc5-bb55-4d7d-b3d9-d91c14a5f22c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1833db7a-fd25-44a8-91b3-40dec8b837db",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "47844e3f-6a0c-47f4-8bda-76a3709878fc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0be3c9c0-2248-47ca-b67a-7b36c81ac1bf",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "10729a4e-2588-4d0e-89ed-f9e69a7d00b9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "99959f37-78b5-4d1c-814d-e210a7bdee0b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "672e62a8-1449-4d5c-8918-cce1fdb382af",
                "ordinal": 3
              }
            ],
            "lineageTag": "7c8e70a9-a692-43d8-9325-512b89339860"
          }
        ],
        "isHidden": true,
        "lineageTag": "72168c4b-9e06-4bcd-a882-a542875bc736",
        "partitions": [
          {
            "name": "LocalDateTable_c0f5b4c3-502d-4d76-a0e5-9a5d52c7bfef",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Data Refresh'[DateTime])), 1, 1), Date(Year(MAX('Data Refresh'[DateTime])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}