{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"PQin_2\",\"Main\",\"Data Refresh\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "PQin_2",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Web.Contents(\"https://southwark.sharepoint.com/sites/ASCServiceDevelopment609/Shared%20Documents/PDQ/Performance%20and%20Quality%20Team/8%20by%208%20call%20log%20analyses/8x8%20report%20generator.xlsm\"), null, true),",
          "    PQin_2_Table = Source{[Item=\"PQin_2\",Kind=\"Table\"]}[Data],",
          "    #\"Changed Type\" = Table.TransformColumnTypes(PQin_2_Table,{{\"Time (Creation)\", type datetime}, {\"Queue Name\", type text}, {\"Channel ID\", type text}, {\"Outcome\", type text}, {\"Labels\", type text}, {\"Customer Name\", type text}, {\"Media Type\", type text}, {\"Direction\", type text}, {\"State\", type text}, {\"Participant\", type text}, {\"Offer Action\", type text}, {\"Busy Duration.1\", Int64.Type}, {\"Busy Duration.2\", Int64.Type}, {\"Busy Duration.3\", Int64.Type}, {\"Wrap Up Code\", type text}, {\"Queue Wait Duration.1\", Int64.Type}, {\"Queue Wait Duration.2\", Int64.Type}, {\"Queue Wait Duration.3\", Int64.Type}, {\"Transaction ID\", Int64.Type}, {\"Interaction Duration.1\", Int64.Type}, {\"Interaction Duration.2\", Int64.Type}, {\"Interaction Duration.3\", Int64.Type}, {\"Interaction duration (mins)\", type number}, {\"Queue Wait Duration (mins)\", type number}, {\"Busy Duration (mins)\", type number}, {\"Total Interaction (mins)\", type number}, {\"Week of Year\", Int64.Type}, {\"Week of\", type text}, {\"Month Name\", type text}, {\"Quarter\", type text}, {\"Day Name\", type text}}),",
          "    #\"Inserted Time\" = Table.AddColumn(#\"Changed Type\", \"Time\", each DateTime.Time([#\"Time (Creation)\"]), type time),",
          "    #\"Inserted Start of Hour\" = Table.AddColumn(#\"Inserted Time\", \"Start of Hour\", each Time.StartOfHour([#\"Time (Creation)\"]), type datetime),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Inserted Start of Hour\",{\"Time (Creation)\", \"Time\", \"Start of Hour\", \"Queue Name\", \"Channel ID\", \"Outcome\", \"Labels\", \"Customer Name\", \"Media Type\", \"Direction\", \"State\", \"Participant\", \"Offer Action\", \"Busy Duration.1\", \"Busy Duration.2\", \"Busy Duration.3\", \"Wrap Up Code\", \"Queue Wait Duration.1\", \"Queue Wait Duration.2\", \"Queue Wait Duration.3\", \"Transaction ID\", \"Interaction Duration.1\", \"Interaction Duration.2\", \"Interaction Duration.3\", \"Interaction duration (mins)\", \"Queue Wait Duration (mins)\", \"Busy Duration (mins)\", \"Total Interaction (mins)\", \"Week of Year\", \"Week of\", \"Month Name\", \"Quarter\", \"Day Name\"}),",
          "    #\"Inserted Year\" = Table.AddColumn(#\"Reordered Columns\", \"Year\", each Date.Year([#\"Time (Creation)\"]), Int64.Type)",
          "in",
          "    #\"Inserted Year\""
        ],
        "kind": "m",
        "lineageTag": "41325093-ccfd-4baa-9a65-51ce7f8c9ea3"
      }
    ],
    "relationships": [
      {
        "name": "4539073c-dd65-4442-a31b-c28cbe83421c",
        "fromColumn": "Time (Creation)",
        "fromTable": "Main",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2886313a-b388-49a3-a8c4-2fa13ac5ff71"
      },
      {
        "name": "e7b06913-4d5a-4cea-851f-56f24cffb684",
        "fromColumn": "Date",
        "fromTable": "Data Refresh",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1fe4404f-40f0-4d42-9b79-f2919780301f"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Main",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Time (Creation)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a0c7a5bb-044a-48d4-8852-36ba36d7dd59",
            "sourceColumn": "Time (Creation)",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2886313a-b388-49a3-a8c4-2fa13ac5ff71"
                },
                "isDefault": true,
                "relationship": "4539073c-dd65-4442-a31b-c28cbe83421c"
              }
            ]
          },
          {
            "name": "Queue Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a26335c-06ea-4fbd-bc1e-3f126b3b926a",
            "sourceColumn": "Queue Name",
            "summarizeBy": "none"
          },
          {
            "name": "Channel ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa1fe4e0-d4dd-411d-8984-cf3e176e89d1",
            "sourceColumn": "Channel ID",
            "summarizeBy": "none"
          },
          {
            "name": "Outcome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf08bc41-4e39-43f0-86bf-c61f82d784cd",
            "sourceColumn": "Outcome",
            "summarizeBy": "none"
          },
          {
            "name": "Labels",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3360bc0c-47f9-4c06-8e71-8305f874f63b",
            "sourceColumn": "Labels",
            "summarizeBy": "none"
          },
          {
            "name": "Direction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29478036-b678-4f6e-a97f-6dd127ff76c2",
            "sourceColumn": "Direction",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54aa6699-37eb-4de6-b3e0-90cd17bbf6a9",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Participant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "025e02d9-cb30-4eac-b4a4-1f68674d22d6",
            "sourceColumn": "Participant",
            "summarizeBy": "none"
          },
          {
            "name": "Offer Action",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "16d6085f-1d72-49bd-b27e-bb311e8cfa87",
            "sortByColumn": "Sort_offer",
            "sourceColumn": "Offer Action",
            "summarizeBy": "none"
          },
          {
            "name": "Wrap Up Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc7280f7-c2c9-4478-8737-bf8ea2fd7cae",
            "sortByColumn": "Sort_wrap",
            "sourceColumn": "Wrap Up Code",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58b80666-0e45-4242-953e-b48580925c51",
            "sourceColumn": "Transaction ID",
            "summarizeBy": "none"
          },
          {
            "name": "Interaction duration (mins)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b05c426a-673c-4f25-a570-55ef110a962f",
            "sourceColumn": "Interaction duration (mins)",
            "summarizeBy": "sum"
          },
          {
            "name": "Queue Wait Duration (mins)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4281faac-69d6-43a5-8071-47d37db0dbc8",
            "sourceColumn": "Queue Wait Duration (mins)",
            "summarizeBy": "sum"
          },
          {
            "name": "Busy Duration (mins)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "29e708b6-19b7-48eb-8d38-9e757d61f49a",
            "sourceColumn": "Busy Duration (mins)",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Interaction (mins)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3fc7e545-33af-4cdc-9e6e-5746edeb0969",
            "sourceColumn": "Total Interaction (mins)",
            "summarizeBy": "sum"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ae2ec3e-1800-412b-a9e0-f2922d2b90ed",
            "sourceColumn": "Week of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Week of",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7de356cc-d4ba-4a7d-8b73-db3a9425b2cb",
            "sourceColumn": "Week of",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8c20926-13a2-400b-960a-a2cdba579e48",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05884ec7-f485-4353-8ccb-a67141dd35a3",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0deb1094-a275-4105-b925-d4b7ce2ed79e",
            "sortByColumn": "Sort_day",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Sort_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "78ee8f7d-6621-4272-b70a-d2ad31663cd1",
            "sourceColumn": "Sort_day",
            "summarizeBy": "sum"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "6cf7b344-2d6d-4680-b9e5-250ba60a5a38",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "hh:nn AM/PM",
            "lineageTag": "f3439526-d434-40e4-8fe8-6ee3de9acccc",
            "sourceColumn": "Start of Hour",
            "summarizeBy": "none"
          },
          {
            "name": "Sort_wrap",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56259b5a-bcc0-4f5b-8130-0e9993fa8f49",
            "sourceColumn": "Sort_wrap",
            "summarizeBy": "none"
          },
          {
            "name": "Sort_offer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d98307e0-d569-48e7-ad9a-30bc504bcf82",
            "sourceColumn": "Sort_offer",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7a34f2f5-6c73-4793-933d-0387d3570159",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR CurrentYear = [Year]",
              "VAR CurrentMonth = VALUE(Main[Time (Creation)].[MonthNo])",
              "VAR FinancialYearStart = IF(CurrentMonth >= 4, CurrentYear, CurrentYear - 1)",
              "VAR FinancialYearEnd = FinancialYearStart + 1",
              "VAR FinancialYearString = RIGHT(FORMAT(FinancialYearStart, \"00\"), 2) & \"/\" & RIGHT(FORMAT(FinancialYearEnd, \"00\"), 2)",
              "RETURN",
              "    FinancialYearString"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "50d5270e-f7c4-4281-a4a5-27c3154714c3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dummy_worker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(Main[Participant]<>\"\", RIGHT(Main[Participant],3),\"\")",
            "isDataTypeInferred": true,
            "lineageTag": "6aa63dc1-ebf5-42cb-ae70-1a11ad68b8cb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Quarter Hierarchy",
            "levels": [
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "aa21223f-b017-4055-92f5-dcfbf2bbeba0",
                "ordinal": 0
              },
              {
                "name": "Month Name",
                "column": "Month Name",
                "lineageTag": "4e8d28fc-5892-4ea7-ab95-179d10a89e5f",
                "ordinal": 1
              }
            ],
            "lineageTag": "bf19e1b6-7ccb-491a-8e2e-491038665b5f"
          }
        ],
        "lineageTag": "c9cc3a4c-6fe2-454d-abe5-b3ff1370e7de",
        "measures": [
          {
            "name": "Busiest_Day_monthly",
            "expression": [
              "",
              "VAR CurrentMonth = ",
              "    SELECTEDVALUE(Main[Month Name])",
              "VAR DayCounts = ",
              "    ADDCOLUMNS(",
              "        VALUES(Main[Day Name]),",
              "        \"TransactionCount\",",
              "        CALCULATE(COUNTA(Main[Transaction ID]), ",
              "        Main[Month Name] = ",
              "        CurrentMonth)",
              "    )",
              "VAR BusiestDay = ",
              "    TOPN(",
              "        1, ",
              "        DayCounts,",
              "        [TransactionCount], ",
              "        DESC",
              "    )",
              "VAR BusiestDayName = ",
              "    MAXX(BusiestDay, [Day Name])",
              "RETURN",
              "    \"The Busiest Day of \" & CurrentMonth & \" is \" & BusiestDayName",
              ""
            ],
            "lineageTag": "600a2c44-ae41-456d-bf35-92fcc5c29cfd"
          },
          {
            "name": "Count_Busiest_Day_monthly",
            "expression": [
              "",
              "VAR CurrentMonth = ",
              "    SELECTEDVALUE(Main[Month Name])",
              "VAR DayCounts = ",
              "    ADDCOLUMNS(",
              "        VALUES(Main[Day Name]),",
              "        \"TransactionCount\",",
              "        CALCULATE(COUNTA(Main[Transaction ID]), ",
              "        Main[Month Name] = ",
              "            CurrentMonth)",
              "    )",
              "VAR BusiestDay = ",
              "    TOPN(",
              "        1, ",
              "        DayCounts,",
              "        [TransactionCount], ",
              "        DESC",
              "    )",
              "RETURN ",
              "    MAXX(BusiestDay, [TransactionCount])",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fa0a1537-c713-469b-b533-d37598ce66cf"
          },
          {
            "name": "Total_title",
            "expression": [
              "",
              "VAR TodayDate = TODAY()",
              "VAR LastMonthDate = EOMONTH(TodayDate, -1)",
              "VAR LastMonthName = FORMAT(LastMonthDate, \"MMMM\")",
              "",
              "RETURN",
              "    \" Total Calls in \" & LastMonthName",
              ""
            ],
            "lineageTag": "9d5a86e5-be32-44de-98e4-6e94043a0fe7"
          },
          {
            "name": "Ratio_Month_Han_aban",
            "expression": [
              "",
              "VAR HandledCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]),",
              "    Main[Outcome] = \"Handled\")",
              "VAR AbandonedCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]),",
              "    Main[Outcome] = \"Abandoned\")",
              "VAR MonthlyRatio = ",
              "    ROUND(HandledCalls / AbandonedCalls,0)",
              "RETURN ",
              "    \"The Ratio of Handled to Abandoned Calls is \" & ",
              "    BLANK() & UNICHAR(10) & ",
              "    BLANK() & UNICHAR(10) &",
              "    MonthlyRatio & \":\" & 1",
              "",
              ""
            ],
            "lineageTag": "b2dbd658-bfee-4d28-a3ef-c30a6ce9449d"
          },
          {
            "name": "Percent_Month_Han_aban",
            "expression": [
              "",
              "VAR HandledCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]),",
              "    Main[Outcome] = \"Handled\")",
              "VAR AbandonedCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]),",
              "    Main[Outcome] = \"Abandoned\")",
              "VAR TotalCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]))    ",
              "VAR HandledProportion = ",
              "    (ROUND(HandledCalls / TotalCalls,2)) * 100",
              "VAR AbandonedProportion = ",
              "    (ROUND(AbandonedCalls / TotalCalls,2)) * 100    ",
              "RETURN ",
              "    \"The Percentage of Handled Calls is \" & ",
              "    BLANK() & UNICHAR(10) & ",
              "    HandledProportion & \"%\" &",
              "    BLANK() & UNICHAR(10) & ",
              "    \"while that of Abandoned Calls is \" & ",
              "    AbandonedProportion & \"%\""
            ],
            "lineageTag": "dbce4c87-d987-4979-817a-5c8278e6678e"
          },
          {
            "name": "Busiest_Queue_monthly",
            "expression": [
              "",
              "VAR CurrentMonth = ",
              "    SELECTEDVALUE(Main[Month Name])",
              "VAR QueueCounts = ",
              "    ADDCOLUMNS(",
              "        VALUES(Main[Queue Name]),",
              "        \"QueueCount\",",
              "        CALCULATE(COUNTA(Main[Transaction ID]), ",
              "        Main[Month Name] = ",
              "            CurrentMonth)",
              "    )",
              "VAR BusiestQueue = ",
              "    TOPN(",
              "        1, ",
              "        QueueCounts,",
              "        [QueueCount], ",
              "        DESC",
              "    )",
              "VAR BusiestQueueName = ",
              "    MAXX(BusiestQueue, [Queue Name])",
              "VAR BusiestQueueCount = ",
              "    MAXX(BusiestQueue, [QueueCount])",
              "VAR TotalCallsInMonth = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]), ",
              "        Main[Month Name] = CurrentMonth)",
              "VAR QueueProportion = ",
              "    DIVIDE(BusiestQueueCount, TotalCallsInMonth, 0) * 100 ",
              "RETURN ",
              "    \"The Busiest Queue in \" & CurrentMonth & \" is \" & BusiestQueueName & \" with \" & FORMAT(QueueProportion, \"0\") & \"% of the Total Number of Calls\" ",
              "",
              ""
            ],
            "lineageTag": "9defb299-4a67-41c7-b882-f2532cb226a3"
          },
          {
            "name": "Busiest_Day_comp",
            "expression": [
              "",
              "VAR Q1 = ",
              "    VAR DayCountsQ1 = ",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Day Name]),",
              "            \"TransactionCount1\",",
              "            CALCULATE(COUNTA(Main[Transaction ID]), ",
              "                Main[Quarter] = \"Quarter 1\")",
              "        )",
              "    VAR BusiestDayQ1 = ",
              "        TOPN(1, ",
              "            DayCountsQ1, ",
              "            [TransactionCount1], ",
              "            DESC)",
              "    VAR BusiestDayNameQ1 = ",
              "        MAXX(BusiestDayQ1, [Day Name])",
              "    VAR BusiestDayCountQ1 = ",
              "        MAXX(BusiestDayQ1, [TransactionCount1])",
              "    RETURN ",
              "        \"Q1: \" & BusiestDayNameQ1 & \", \" & BusiestDayCountQ1 & \" calls\"",
              "VAR Q2 = ",
              "    VAR DayCountsQ2 = ",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Day Name]),",
              "            \"TransactionCount2\",",
              "            CALCULATE(COUNTA(Main[Transaction ID]), ",
              "                Main[Quarter] = \"Quarter 2\")",
              "        )",
              "    VAR BusiestDayQ2 = ",
              "        TOPN(1, ",
              "            DayCountsQ2, ",
              "            [TransactionCount2], ",
              "            DESC)",
              "    VAR BusiestDayNameQ2 = ",
              "        MAXX(BusiestDayQ2, [Day Name])",
              "    VAR BusiestDayCountQ2 = ",
              "        MAXX(BusiestDayQ2, [TransactionCount2])",
              "    RETURN ",
              "        \"Q2: \" & BusiestDayNameQ2 & \", \" & BusiestDayCountQ2 & \" calls\"",
              "VAR Q3 = ",
              "    VAR DayCountsQ3 = ",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Day Name]),",
              "            \"TransactionCount3\",",
              "            CALCULATE(COUNTA(Main[Transaction ID]), ",
              "                Main[Quarter] = \"Quarter 3\")",
              "        )",
              "    VAR BusiestDayQ3 = ",
              "        TOPN(1, ",
              "            DayCountsQ3, ",
              "            [TransactionCount3], ",
              "            DESC)",
              "    VAR BusiestDayNameQ3 = ",
              "        MAXX(BusiestDayQ3, [Day Name])",
              "    VAR BusiestDayCountQ3 = ",
              "        MAXX(BusiestDayQ3, [TransactionCount3])",
              "    RETURN ",
              "        \"Q3: \" & BusiestDayNameQ3 & \", \" & BusiestDayCountQ3 & \" calls\"    ",
              "VAR Q4 = ",
              "    VAR DayCountsQ4 = ",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Day Name]),",
              "            \"TransactionCount4\",",
              "            CALCULATE(COUNTA(Main[Transaction ID]), ",
              "                Main[Quarter] = \"Quarter 4\")",
              "        )",
              "    VAR BusiestDayQ4 = ",
              "        TOPN(1, ",
              "            DayCountsQ4, ",
              "            [TransactionCount4], ",
              "            DESC)",
              "    VAR BusiestDayNameQ4 = ",
              "        MAXX(BusiestDayQ4, [Day Name])",
              "    VAR BusiestDayCountQ4 = ",
              "        MAXX(BusiestDayQ4, [TransactionCount4])",
              "    RETURN ",
              "        \"Q4: \" & BusiestDayNameQ4 & \", \" & BusiestDayCountQ4 & \" calls\"",
              "RETURN",
              "    Q1 & UNICHAR(10) & Q2 & UNICHAR(10) & Q3 & UNICHAR(10) & Q4"
            ],
            "lineageTag": "eabf9868-8201-4101-84c8-aad96cc79c53"
          },
          {
            "name": "Ratio_Comp_Han_aban",
            "expression": [
              "",
              "VAR HandledCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]),",
              "    Main[Outcome] = \"Handled\")",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"All Time\")",
              "VAR AbandonedCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]),",
              "    Main[Outcome] = \"Abandoned\")",
              "VAR MonthlyRatio = ",
              "    ROUND(HandledCalls / AbandonedCalls,0)",
              "RETURN ",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"The Ratio of Handled to Abandoned Calls for All Time is \" & ",
              "        BLANK() & UNICHAR(10) & ",
              "        BLANK() & UNICHAR(10) &",
              "        MonthlyRatio & \":\" & 1,",
              "        \"The Ratio of Handled to Abandoned Calls for \" & SingleFY & \" is \" & ",
              "        BLANK() & UNICHAR(10) & ",
              "        BLANK() & UNICHAR(10) &",
              "        MonthlyRatio & \":\" & 1",
              "    )",
              "",
              "",
              "    ",
              "",
              ""
            ],
            "lineageTag": "3fa7bfa8-a932-4bbf-a7e2-6d91c55345f2"
          },
          {
            "name": "Percent_Comp_Han_aban",
            "expression": [
              "",
              "VAR HandledCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]),",
              "    Main[Outcome] = \"Handled\")",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = ",
              "    IF(",
              "        DistinctFYCount = 1, ",
              "        MAX(Main[Financial Year]), ",
              "        \"All Time\"",
              "    )",
              "VAR AbandonedCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]),",
              "    Main[Outcome] = \"Abandoned\")",
              "VAR TotalCalls = ",
              "    CALCULATE(COUNTA(Main[Transaction ID]))    ",
              "VAR HandledProportion = ",
              "    (ROUND(HandledCalls / TotalCalls,2)) * 100",
              "VAR AbandonedProportion = ",
              "    (ROUND(AbandonedCalls / TotalCalls,2)) * 100    ",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])), ",
              "        \"All Time, the percentage of Handled Calls is \" & ",
              "        BLANK() & UNICHAR(10) & ",
              "        HandledProportion & \"%\" &",
              "        BLANK() & UNICHAR(10) & ",
              "        \"while that of Abandoned Calls is \" & ",
              "        AbandonedProportion & \"%\",",
              "        \"For \"  & SingleFY & \", the percentage of Handled Calls is \" & ",
              "        BLANK() & UNICHAR(10) & ",
              "        HandledProportion & \"%\" &",
              "        BLANK() & UNICHAR(10) & ",
              "        \"while that of Abandoned Calls is \" & ",
              "        AbandonedProportion & \"%\")"
            ],
            "lineageTag": "a4840c55-43b0-4305-b7b8-87c5f058f006"
          },
          {
            "name": "Busiest_Queue_comp",
            "expression": [
              "",
              "VAR Q1 = ",
              "    VAR QueueCountsQ1 = ",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Queue Name]),",
              "            \"QueueCount1\",",
              "            CALCULATE(COUNTA(Main[Transaction ID]), ",
              "                Main[Quarter] = \"Quarter 1\")",
              "        )",
              "    VAR BusiestQueueQ1 = ",
              "        TOPN(1, ",
              "            QueueCountsQ1, ",
              "            [QueueCount1], ",
              "            DESC)",
              "    VAR BusiestQueueNameQ1 = ",
              "        MAXX(BusiestQueueQ1, [Queue Name])",
              "    VAR BusiestQueueCountQ1 = ",
              "        MAXX(BusiestQueueQ1, [QueueCount1])",
              "    RETURN ",
              "        \"Q1: \" & BusiestQueueNameQ1 & \", \" & BusiestQueueCountQ1 & \" calls\"",
              "VAR Q2 = ",
              "    VAR QueueCountsQ2 = ",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Queue Name]),",
              "            \"QueueCount2\",",
              "            CALCULATE(COUNTA(Main[Transaction ID]), ",
              "                Main[Quarter] = \"Quarter 2\")",
              "        )",
              "    VAR BusiestQueueQ2 = ",
              "        TOPN(1, ",
              "            QueueCountsQ2, ",
              "            [QueueCount2], ",
              "            DESC)",
              "    VAR BusiestQueueNameQ2 = ",
              "        MAXX(BusiestQueueQ2, [Queue Name])",
              "    VAR BusiestQueueCountQ2 = ",
              "        MAXX(BusiestQueueQ2, [QueueCount2])",
              "    RETURN ",
              "        \"Q2: \" & BusiestQueueNameQ2 & \", \" & BusiestQueueCountQ2 & \" calls\"",
              "VAR Q3 = ",
              "    VAR QueueCountsQ3 = ",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Queue Name]),",
              "            \"QueueCount3\",",
              "            CALCULATE(COUNTA(Main[Transaction ID]), ",
              "                Main[Quarter] = \"Quarter 3\")",
              "        )",
              "    VAR BusiestQueueQ3 = ",
              "        TOPN(1, ",
              "            QueueCountsQ3, ",
              "            [QueueCount3], ",
              "            DESC)",
              "    VAR BusiestQueueNameQ3 = ",
              "        MAXX(BusiestQueueQ3, [Queue Name])",
              "    VAR BusiestQueueCountQ3 = ",
              "        MAXX(BusiestQueueQ3, [QueueCount3])",
              "    RETURN ",
              "        \"Q3: \" & BusiestQueueNameQ3 & \", \" & BusiestQueueCountQ3 & \" calls\"    ",
              "VAR Q4 = ",
              "    VAR QueueCountsQ4 = ",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Queue Name]),",
              "            \"QueueCount4\",",
              "            CALCULATE(COUNTA(Main[Transaction ID]), ",
              "                Main[Quarter] = \"Quarter 4\")",
              "        )",
              "    VAR BusiestQueueQ4 = ",
              "        TOPN(1, ",
              "            QueueCountsQ4, ",
              "            [QueueCount4], ",
              "            DESC)",
              "    VAR BusiestQueueNameQ4 = ",
              "        MAXX(BusiestQueueQ4, [Queue Name])",
              "    VAR BusiestQueueCountQ4 = ",
              "        MAXX(BusiestQueueQ4, [QueueCount4])",
              "    RETURN ",
              "        \"Q4: \" & BusiestQueueNameQ4 & \", \" & BusiestQueueCountQ4 & \" calls\"",
              "RETURN",
              "    Q1 & UNICHAR(10) & UNICHAR(10) & Q2 & UNICHAR(10) & UNICHAR(10) & Q3 & UNICHAR(10) & UNICHAR(10) & Q4"
            ],
            "lineageTag": "817033cc-110b-4660-a3ef-7d66c94d2fbd"
          },
          {
            "name": "Total_title_comp",
            "expression": [
              "",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"- All Time\")",
              "",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"Total calls - All Time\",",
              "        \"Total Calls in \" & SingleFY",
              "    )"
            ],
            "lineageTag": "a1b142fe-b780-40de-b7f4-81cf8691524d"
          },
          {
            "name": "Busiest_title_comp",
            "expression": [
              "",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"- All Time\")",
              "",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"Busiest Day - All Time\",",
              "        \"Busiest Day in \" & SingleFY",
              "    )"
            ],
            "lineageTag": "32676c64-946b-4e3e-93c5-126d327bb234"
          },
          {
            "name": "Busiest_Day_comp2",
            "expression": [
              "",
              "VAR SelectedFinancialYear =",
              "    SELECTEDVALUE(Main[Financial Year])",
              "VAR AvailableMonths =",
              "    DISTINCT(Main[Month Name])",
              "VAR MonthCount =",
              "    COUNTROWS(AvailableMonths)",
              "VAR Q1 =",
              "    VAR DayCountsQ1 =",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Day Name]),",
              "            \"TransactionCount1\",",
              "            CALCULATE(",
              "                COUNTA(Main[Transaction ID]),",
              "                Main[Quarter] = \"Quarter 1\"",
              "            )",
              "        )",
              "    VAR BusiestDayQ1 =",
              "        TOPN(",
              "            1,",
              "            DayCountsQ1,",
              "            [TransactionCount1],",
              "            DESC",
              "        )",
              "    VAR BusiestDayNameQ1 =",
              "        MAXX(BusiestDayQ1, [Day Name])",
              "    VAR BusiestDayCountQ1 =",
              "        MAXX(BusiestDayQ1, [TransactionCount1])",
              "    RETURN",
              "        IF(",
              "            SelectedFinancialYear = \"25/26\",",
              "            VAR MonthForQ1 = MINX(FILTER(Main, Main[Quarter] = \"Quarter 1\"), Main[Month Name])",
              "            RETURN",
              "                MonthForQ1 & \": \" & BusiestDayNameQ1 & \", \" & BusiestDayCountQ1 & \" calls\",",
              "            \"Q1: \" & BusiestDayNameQ1 & \", \" & BusiestDayCountQ1 & \" calls\"",
              "        )",
              "VAR Q2 =",
              "    VAR DayCountsQ2 =",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Day Name]),",
              "            \"TransactionCount2\",",
              "            CALCULATE(",
              "                COUNTA(Main[Transaction ID]),",
              "                Main[Quarter] = \"Quarter 2\"",
              "            )",
              "        )",
              "    VAR BusiestDayQ2 =",
              "        TOPN(",
              "            1,",
              "            DayCountsQ2,",
              "            [TransactionCount2],",
              "            DESC",
              "        )",
              "    VAR BusiestDayNameQ2 =",
              "        MAXX(BusiestDayQ2, [Day Name])",
              "    VAR BusiestDayCountQ2 =",
              "        MAXX(BusiestDayQ2, [TransactionCount2])",
              "    RETURN",
              "        IF(",
              "            SelectedFinancialYear = \"25/26\",",
              "            VAR MonthForQ2 = MINX(FILTER(Main, Main[Quarter] = \"Quarter 2\"), Main[Month Name])",
              "            RETURN",
              "                MonthForQ2 & \": \" & BusiestDayNameQ2 & \", \" & BusiestDayCountQ2 & \" calls\",",
              "            \"Q2: \" & BusiestDayNameQ2 & \", \" & BusiestDayCountQ2 & \" calls\"",
              "        )",
              "VAR Q3 =",
              "    VAR DayCountsQ3 =",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Day Name]),",
              "            \"TransactionCount3\",",
              "            CALCULATE(",
              "                COUNTA(Main[Transaction ID]),",
              "                Main[Quarter] = \"Quarter 3\"",
              "            )",
              "        )",
              "    VAR BusiestDayQ3 =",
              "        TOPN(",
              "            1,",
              "            DayCountsQ3,",
              "            [TransactionCount3],",
              "            DESC",
              "        )",
              "    VAR BusiestDayNameQ3 =",
              "        MAXX(BusiestDayQ3, [Day Name])",
              "    VAR BusiestDayCountQ3 =",
              "        MAXX(BusiestDayQ3, [TransactionCount3])",
              "    RETURN",
              "        IF(",
              "            SelectedFinancialYear = \"25/26\",",
              "            VAR MonthForQ3 = MINX(FILTER(Main, Main[Quarter] = \"Quarter 3\"), Main[Month Name])",
              "            RETURN",
              "                MonthForQ3 & \": \" & BusiestDayNameQ3 & \", \" & BusiestDayCountQ3 & \" calls\",",
              "            \"Q3: \" & BusiestDayNameQ3 & \", \" & BusiestDayCountQ3 & \" calls\"",
              "        )",
              "VAR Q4 =",
              "    VAR DayCountsQ4 =",
              "        ADDCOLUMNS(",
              "            VALUES(Main[Day Name]),",
              "            \"TransactionCount4\",",
              "            CALCULATE(",
              "                COUNTA(Main[Transaction ID]),",
              "                Main[Quarter] = \"Quarter 4\"",
              "            )",
              "        )",
              "    VAR BusiestDayQ4 =",
              "        TOPN(",
              "            1,",
              "            DayCountsQ4,",
              "            [TransactionCount4],",
              "            DESC",
              "        )",
              "    VAR BusiestDayNameQ4 =",
              "        MAXX(BusiestDayQ4, [Day Name])",
              "    VAR BusiestDayCountQ4 =",
              "        MAXX(BusiestDayQ4, [TransactionCount4])",
              "    RETURN",
              "        IF(",
              "            SelectedFinancialYear = \"25/26\",",
              "            VAR MonthForQ4 = MINX(FILTER(Main, Main[Quarter] = \"Quarter 4\"), Main[Month Name])",
              "            RETURN",
              "                MonthForQ4 & \": \" & BusiestDayNameQ4 & \", \" & BusiestDayCountQ4 & \" calls\",",
              "            \"Q4: \" & BusiestDayNameQ4 & \", \" & BusiestDayCountQ4 & \" calls\"",
              "        )",
              "RETURN",
              "    ",
              "    Q1 & UNICHAR(10) & Q2 & UNICHAR(10) & Q3 & UNICHAR(10) & Q4"
            ],
            "lineageTag": "bc953f39-554b-410b-a932-ce4a26505177"
          },
          {
            "name": "Graph_title_comp",
            "expression": [
              "",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"- All Time\")",
              "",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"Daily Calls - All Time\",",
              "        \"Daily Calls in \" & SingleFY",
              "    )"
            ],
            "lineageTag": "995f56df-4939-499f-838f-797e554afe92"
          },
          {
            "name": "Table_aban_title_comp",
            "expression": [
              "",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"All Time\")",
              "",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"All Time Comparison of Abandoned Calls\",",
              "        SingleFY & \" Comparison of Abandoned Calls \" ",
              "    )"
            ],
            "lineageTag": "4f4b1542-31e6-4282-969f-5cb25d7100f6"
          },
          {
            "name": "Table_han_title_comp",
            "expression": [
              "",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"All Time\")",
              "",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"All Time Comparison of Handled Calls\",",
              "        SingleFY & \" Comparison of Handled Calls \" ",
              "    )"
            ],
            "lineageTag": "03fb2d18-7cf5-43ca-8c3b-0c6a6ac2cef7"
          },
          {
            "name": "Busiest_Queue_title_comp",
            "expression": [
              "",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"- All Time\")",
              "",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"Busiest Queues - All Time\",",
              "        \"Busiest Queues in \" & SingleFY",
              "    )"
            ],
            "lineageTag": "f8c7eb83-31d2-4570-ad3b-29bb1c6fa142"
          },
          {
            "name": "Wrapup_title_comp",
            "expression": [
              "",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"- All Time\")",
              "",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"Wrap up Codes - All Time\",",
              "        \"Wrap up Codes in \" & SingleFY",
              "    )"
            ],
            "lineageTag": "1ffe6f93-8296-4720-a6b0-f7a622c3fe33"
          },
          {
            "name": "Labels_title_comp",
            "expression": [
              "",
              "VAR SelectedFY = ALLSELECTED(Main[Financial Year])",
              "VAR IsFilterApplied = ISFILTERED(Main[Financial Year])",
              "VAR DistinctFYCount = COUNTROWS(DISTINCT(SelectedFY))",
              "VAR SingleFY = IF(DistinctFYCount = 1, MAX(Main[Financial Year]), \"- All Time\")",
              "",
              "RETURN",
              "    IF(",
              "        NOT IsFilterApplied || DistinctFYCount = COUNTROWS(ALL(Main[Financial Year])),",
              "        \"Labels by Offer Action - All Time\",",
              "        \"Labels by Offer Action in \" & SingleFY",
              "    )"
            ],
            "lineageTag": "a150cb97-0aa4-429a-ad88-de60ec8b536a"
          }
        ],
        "partitions": [
          {
            "name": "Main",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PQin_2,",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"Busy Duration.1\", \"Busy Duration.2\", \"Customer Name\", \"Media Type\", \"Busy Duration.3\", \"Queue Wait Duration.1\", \"Queue Wait Duration.2\", \"Queue Wait Duration.3\", \"Interaction Duration.1\", \"Interaction Duration.2\", \"Interaction Duration.3\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Day Name\", type text}, {\"Quarter\", type text}, {\"Month Name\", type text}, {\"Week of\", type text}, {\"Week of Year\", Int64.Type}, {\"Total Interaction (mins)\", type number}, {\"Busy Duration (mins)\", type number}, {\"Queue Wait Duration (mins)\", type number}, {\"Interaction duration (mins)\", type number}, {\"Transaction ID\", type text}, {\"Wrap Up Code\", type text}, {\"Offer Action\", type text}, {\"Participant\", type text}, {\"State\", type text}, {\"Direction\", type text}, {\"Channel ID\", type text}, {\"Queue Name\", type text}}),",
                "    #\"Added Sort_day Column\" = Table.AddColumn(#\"Changed Type\", \"Sort_day\", each if [Day Name] = \"Friday\" then 5 else if [Day Name] = \"Thursday\" then 4 else if [Day Name] = \"Wednesday\" then 3 else if [Day Name] = \"Tuesday\" then 2 else 1, type number),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Sort_day Column\",{{\"Start of Hour\", type time}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type1\",\"\",\"Not recorded\",Replacer.ReplaceValue,{\"Wrap Up Code\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"\",\"Not recorded\",Replacer.ReplaceValue,{\"Offer Action\"}),",
                "    #\"Added Sort_wrap Column\" = Table.AddColumn(#\"Replaced Value1\", \"Sort_wrap\", each if [Wrap Up Code] = \"Not recorded\" then 1 else 2),",
                "    #\"Added Sort_offer Column\" = Table.AddColumn(#\"Added Sort_wrap Column\", \"Sort_offer\", each if [Offer Action] = \"Not recorded\" then 1 else 2)",
                "in",
                "    #\"Added Sort_offer Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ae75fcca-5220-4138-9e8f-c93e223dee97",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7e8a06dc-ecf5-432f-a6bc-34cac51d918b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2eaedeaf-4bfd-4540-9ecd-a2abffe8be0c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "57a7bdae-1563-484d-8832-21cb8f382c06",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5e9345ac-a270-485e-9996-07373c89cb96",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5c61eef5-5f55-4e45-85e8-7f85014804b6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "89bd9d09-66f0-4873-9422-4099b7b04b86",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "417acd28-d31a-418b-bdcd-f4d3c6a6bc33",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "49ff9b63-f7a5-48ef-963a-8b1e93f3a5b0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "514cb2f6-a3d3-4f0e-8588-e019b0e6558a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3e2f03ff-583f-4639-a433-b526c5b80d28",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "34c58883-1f87-4394-b1d2-604ed770275f",
                "ordinal": 3
              }
            ],
            "lineageTag": "53fbf096-8543-4901-b570-3bdf9a55116a"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2f43d3c8-06b8-4eed-a6c2-bbd8018869f5",
        "partitions": [
          {
            "name": "DateTableTemplate_ae75fcca-5220-4138-9e8f-c93e223dee97",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2886313a-b388-49a3-a8c4-2fa13ac5ff71",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d9d4dec7-0ebc-403e-9b14-ca810f147374",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fce94d3c-986a-44ff-92ad-b4c42584a5ab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "124cd876-3cb3-4f6b-a04c-a320476b958a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0014d5a7-9929-433b-bda9-1353dc623f32",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f435d4a6-9a0c-4389-835f-83276720d06b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3a5393a6-b655-42e1-bdb7-81be5542bd3b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2ed07061-d7d6-47e3-a237-06ae7d4d3454",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4ec7bf64-ad6c-413f-94e5-2b2bc161438e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c67d6f86-bb91-4a85-a1f6-4329981866bd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ee788048-b22c-4699-8843-52dae3e48d52",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ad814634-4085-41b9-b4d6-b8444a27a0a9",
                "ordinal": 3
              }
            ],
            "lineageTag": "e8ac625f-44ae-4e99-9f52-367aa1a3d341"
          }
        ],
        "isHidden": true,
        "lineageTag": "b331dea5-7643-4c22-959c-901903a9e624",
        "partitions": [
          {
            "name": "LocalDateTable_2886313a-b388-49a3-a8c4-2fa13ac5ff71",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Main'[Time (Creation)])), 1, 1), Date(Year(MAX('Main'[Time (Creation)])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Data Refresh",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "248d58bb-09b4-4bda-be64-5147a0c2fcd9",
            "sourceColumn": "DateTime",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "391b5a96-92ce-4201-a6b7-280f7061e1f0",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1fe4404f-40f0-4d42-9b79-f2919780301f"
                },
                "isDefault": true,
                "relationship": "e7b06913-4d5a-4cea-851f-56f24cffb684"
              }
            ]
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "c8dfec64-4c7d-4f43-9d3e-bc68ffcc96d5",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ecfc2e1c-3018-4f90-b61d-bada499b3050",
        "partitions": [
          {
            "name": "Data Refresh",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DateTime.LocalNow(),",
                "    #\"Converted to Table\" = #table(1, {{Source}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"DateTime\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns\", \"DateTime\", \"DateTime - Copy\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"DateTime - Copy\", \"Date\"}}),",
                "    #\"Extracted Date\" = Table.TransformColumns(#\"Renamed Columns1\",{{\"Date\", DateTime.Date, type date}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Extracted Date\", \"DateTime\", \"DateTime - Copy\"),",
                "    #\"Extracted Time\" = Table.TransformColumns(#\"Duplicated Column1\",{{\"DateTime - Copy\", DateTime.Time, type time}}),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Extracted Time\",{{\"DateTime - Copy\", \"Time\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1fe4404f-40f0-4d42-9b79-f2919780301f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bd2cf092-09af-4949-84a4-e588cc419325",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7ffa7627-c7bd-45c9-8ed5-88450b86cb3b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e4333c48-5cb2-4058-85f0-37bbdca74185",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "da3d1371-735e-418b-83da-572e1b944409",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a0b15b71-d9f9-4563-9d28-d20f4136bdf1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5a2afb43-c724-42d9-982c-775019c302e7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea7675d4-58f9-446c-a6fc-bfb02915b9ac",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "81c9023c-9983-4b5c-9c3f-a894483f6a65",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9df1f518-352d-4cb9-93cd-1ec6f3429e41",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a2555b47-ace6-4f26-b08d-a1d40f6a35b2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5c959f0f-49a6-446b-acac-109782e49fe5",
                "ordinal": 3
              }
            ],
            "lineageTag": "a366de39-20b1-4d6c-84af-7e9ce332146b"
          }
        ],
        "isHidden": true,
        "lineageTag": "b2364db0-bf5c-4fc8-a7e6-898ce87d24d2",
        "partitions": [
          {
            "name": "LocalDateTable_1fe4404f-40f0-4d42-9b79-f2919780301f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Data Refresh'[Date])), 1, 1), Date(Year(MAX('Data Refresh'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}