table 'Person IDs'
	lineageTag: 9a3e28a1-24ba-4354-adac-7bf350e4493c

	column 'Person ID'
		dataType: string
		lineageTag: 5558fba0-0d27-49f5-aab4-6ccbf7e85434
		summarizeBy: none
		sourceColumn: Person ID

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Started On'
		dataType: dateTime
		formatString: General Date
		lineageTag: cd0ef36e-b483-4ea6-b0c1-7ab724a10fb4
		summarizeBy: none
		sourceColumn: Started On

		variation Variation
			isDefault
			relationship: b6e22b45-3c11-457e-994a-db55a48f35b1
			defaultHierarchy: LocalDateTable_98c1748f-4f5e-4b29-b134-a52086e4bf91.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Step ID'
		dataType: int64
		formatString: 0
		lineageTag: a4ad1830-5918-45cb-9f20-fb35806a1c34
		summarizeBy: count
		sourceColumn: Step ID

		annotation SummarizationSetBy = Automatic

	column dummy_ID = IF('Person IDs'[Person ID]<>"",RIGHT('Person IDs'[Person ID],3), "")
		lineageTag: dde056f5-179c-4bc6-88d0-992c89e62d7a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Person IDs' = m
		mode: import
		source =
				let
				    Source = OPPD_Referrals_in_period_front_door,
				    #"Removed Other Columns1" = Table.SelectColumns(Source,{"Person ID", "Step ID", "Started On"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns1", {"Person ID"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

